import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import * as contentful from 'contentful'

type ContentfulData = {
  header?: string,
  email?: string
};

let client = contentful.createClient({
  space: process.env.CONTENT_SPACE_ID as string,
  accessToken: process.env.CONTENT_ACCESS_TOKEN as string,
});

const Home: NextPage = (props:ContentfulData) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>New Nuevo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {props.header}
        </h1>
        <div>
          {props.email}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home


export async function getStaticProps() {
  const data = await client.getEntry('6Ildm9AXKqXUUChAAJKLNT');

  return {
    props: {
      ...data.fields as object,
    },
  }
}
