import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import * as contentful from 'contentful'

type ContentfulData = {
  header?: string,
  email?: string
};

let client = contentful.createClient({
  space: process.env.CONTENT_SPACE_ID as string,
  accessToken: process.env.CONTENT_ACCESS_TOKEN as string,
});

const Home: NextPage = (props:ContentfulData) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>New Nuevo: Creative Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicons/favicon.ico" />
        <link rel="apple-touch-icon" sizes="57x57" href="/favicons/apple-icon-57x57.png" />
        <link rel="apple-touch-icon" sizes="60x60" href="/favicons/apple-icon-60x60.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="/favicons/apple-icon-72x72.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="/favicons/apple-icon-76x76.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="/favicons/apple-icon-114x114.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="/favicons/apple-icon-120x120.png" />
        <link rel="apple-touch-icon" sizes="144x144" href="/favicons/apple-icon-144x144.png" />
        <link rel="apple-touch-icon" sizes="152x152" href="/favicons/apple-icon-152x152.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-icon-180x180.png" />
        <link rel="icon" type="image/png" sizes="192x192"  href="/favicons/android-icon-192x192.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="96x96" href="/favicons/favicon-96x96.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png" />
        <meta name="msapplication-TileImage" content="/favicons/ms-icon-144x144.png" />

        <meta property="og:url" content="https://newnuevo.com/" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="newnuevo" />
        <meta property="og:description" content="Creative Digital Studio specialising in software development and design" />
        <meta property="og:image" content="" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="newnuevo.com" />
        <meta property="twitter:url" content="https://newnuevo.com/" />
        <meta name="twitter:title" content="newnuevo" />
        <meta name="twitter:description" content="Creative Digital Studio specialising in software development and design" />
        <meta name="twitter:image" content="" />
      </Head>

      <main className={styles.main}>
        <svg width="150" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" x="0" y="0" viewBox="0 0 260 157.35" className="logo"><path d="M245.82 142.41h13.66v13.66h-13.66v-13.66z" fill="#ff5b55"></path> <path d="M35 39.6L17.93 1H1.57v73.9h16.46V38.36L35 74.9h16.46V1H35zM149.21 1l-6.32 44.61L134.61 1h-13.35l-8.38 44.61L106.67 1h-49v73.9h34.36V60.51H74.12V44.36h12.73V29.98H74.12V15.39h17.91v-.84L104.7 74.9h16.46l6.73-37.68 6.83 37.68h16.45L166.7 1z"></path> <path d="M35 119.7L17.93 81.1H1.57v73.89h16.46v-36.53L35 154.99h16.46V81.1H35zM88.71 122.18c0 16.35-.93 20.49-7.14 20.49s-7.14-4.14-7.14-20.49V81.1H57.67v41.09c0 28.88 4.76 34.05 23.91 34.05s23.91-5.17 23.91-34.05V81.1H88.71v41.08zM174.77 81.1l-8.38 49.57-8.28-49.57h-46.42v73.89h34.36v-14.38h-17.91v-16.15h12.73v-14.39h-12.73V95.48h15.9l14.17 59.51h16.46l17.59-73.89zM216.16 79.85c-22.25 0-23.91 11.38-23.91 38.29 0 27.84 1.66 38.09 23.91 38.09s23.91-10.25 23.91-38.09c0-26.9-1.65-38.29-23.91-38.29zm0 62c-5.17 0-5.8-3.21-5.8-23.7 0-20.08.62-23.91 5.8-23.91 5.17 0 5.8 3.83 5.8 23.91 0 20.49-.62 23.7-5.8 23.7z"></path></svg>
        <section className="main__content">
          <h1 className="header-text">
            {props.header}
          </h1>
          <div className="header-email">
            {props.email}
          </div>
        </section>
        <div>
          <div className="icon__wrapper">
            <a href="https://instagram.com/thenewnuevo" target="_blank" className="icon__social" rel="noreferrer">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"></path></svg>
            </a>
            <a href="https://twitter.com/thenewnuevo" rel="noreferrer" target="_blank" className="icon__social">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path></svg>
            </a>
          </div>
        </div>
        <div>
          <a href="https://www.google.co.uk/maps/place/Creative+Works/@51.5886675,-0.0420934,17z/data=!3m1!4b1!4m5!3m4!1s0x48761dd1e1d2ff2d:0x3298c94ad8dc5a6c!8m2!3d51.5886642!4d-0.0399047" target="_blank" rel="noreferrer" className="address">
            <strong>Creative Works</strong>, First Floor, 7 Blackhorse Lane, London, E17 6DS
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" className="icon__map"><path d="M12 0c-4.198 0-8 3.403-8 7.602 0 4.198 3.469 9.21 8 16.398 4.531-7.188 8-12.2 8-16.398 0-4.199-3.801-7.602-8-7.602zm0 11c-1.657 0-3-1.343-3-3s1.343-3 3-3 3 1.343 3 3-1.343 3-3 3z"></path></svg>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home


export async function getStaticProps() {
  const data = await client.getEntry('6Ildm9AXKqXUUChAAJKLNT');

  return {
    props: {
      ...data.fields as object,
    },
  }
}
